name: auth
description: Server application for managing users.
version: 1.0.0

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  hive: ^2.2.3
  lints: ^2.0.0

dev_dependencies:
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
 
