services:
  auth:
    image: ottorohenkohl/lyria-auth:latest
    build: ../auth/
    container_name: lyria.service.auth
    restart: always
    environment:
      - API_HOST=localhost
      - APO_PATH=/
      - USER_USERNAME=[USERNAME]
      - USER_PASSWORD=[PASSWORD]
      - USER_ROLE=[ROLE]
    ports:
      - 8080:80
    networks:
      - lyria.network
    volumes:
      - lyria.volume.auth:/data

networks:
  lyria.network:
    name: lyria.network
    driver: bridge

volumes:
  lyria.volume.auth:
