services:
  auth:
    image: ottorohenkohl/lyria-auth:latest
    build: ../auth/Dockerfile
    container_name: lyria.service.auth
    environment:
      - API_HOST=localhost
      - APO_PATH=/
    networks:
      - lyria.network
    volumes:
      - lyria.volume.auth:/data

networks:
  lyria.network:
    name: lyria.network
    driver: bridge

volumes:
  lyria.volume.auth:
